// Word lists for Cloud Functions
// Points: easy=10, normal=20, hard=25, insane=50
// Each category has 300 words with mix of topics: general, science, movies, animals, food, technology, etc.

const WORD_LISTS = {
  easy: [
    // Animals (40)
    "DOG", "CAT", "BIRD", "FISH", "HORSE", "COW", "PIG", "CHICKEN", "DUCK", "RABBIT",
    "MOUSE", "FROG", "SNAKE", "TURTLE", "BEAR", "LION", "TIGER", "ELEPHANT", "MONKEY", "ZEBRA",
    "GIRAFFE", "DEER", "FOX", "WOLF", "SHEEP", "GOAT", "DONKEY", "CAMEL", "PENGUIN", "OWL",
    "EAGLE", "PARROT", "SHARK", "WHALE", "DOLPHIN", "CRAB", "LOBSTER", "BEE", "ANT", "SPIDER",
    // Food & Drinks (40)
    "PIZZA", "BURGER", "SANDWICH", "SALAD", "SOUP", "PASTA", "RICE", "BREAD", "BUTTER", "CHEESE",
    "MILK", "JUICE", "COFFEE", "TEA", "WATER", "SODA", "BEER", "WINE", "CAKE", "COOKIE",
    "CANDY", "ICE CREAM", "CHOCOLATE", "POPCORN", "CHIPS", "EGGS", "BACON", "STEAK", "CHICKEN", "FISH",
    "SHRIMP", "TACO", "BURRITO", "NOODLES", "CEREAL", "YOGURT", "PANCAKE", "WAFFLE", "DONUT", "MUFFIN",
    // Fruits & Vegetables (30)
    "APPLE", "BANANA", "ORANGE", "GRAPE", "LEMON", "LIME", "MANGO", "PEACH", "PEAR", "CHERRY",
    "STRAWBERRY", "BLUEBERRY", "WATERMELON", "PINEAPPLE", "COCONUT", "TOMATO", "POTATO", "CARROT", "ONION", "GARLIC",
    "LETTUCE", "SPINACH", "BROCCOLI", "CORN", "BEANS", "PEPPER", "CUCUMBER", "CELERY", "MUSHROOM", "AVOCADO",
    // Household Items (35)
    "CHAIR", "TABLE", "BED", "SOFA", "DESK", "LAMP", "MIRROR", "CLOCK", "DOOR", "WINDOW",
    "CARPET", "CURTAIN", "PILLOW", "BLANKET", "TOWEL", "SOAP", "SHAMPOO", "TOOTHBRUSH", "COMB", "SCISSORS",
    "KNIFE", "FORK", "SPOON", "PLATE", "BOWL", "CUP", "GLASS", "POT", "PAN", "OVEN",
    "FRIDGE", "SINK", "TOILET", "SHOWER", "BATHTUB",
    // Technology (25)
    "PHONE", "COMPUTER", "LAPTOP", "TABLET", "CAMERA", "RADIO", "SPEAKER", "HEADPHONES", "MOUSE", "KEYBOARD",
    "SCREEN", "PRINTER", "REMOTE", "BATTERY", "CHARGER", "WIFI", "EMAIL", "VIDEO", "PHOTO", "GAME",
    "ROBOT", "DRONE", "WATCH", "ALARM", "CALCULATOR",
    // Transportation (25)
    "CAR", "BUS", "TRAIN", "PLANE", "BOAT", "SHIP", "BIKE", "MOTORCYCLE", "TRUCK", "TAXI",
    "SUBWAY", "HELICOPTER", "ROCKET", "SCOOTER", "SKATEBOARD", "AMBULANCE", "FIRETRUCK", "TRACTOR", "VAN", "JEEP",
    "CANOE", "FERRY", "YACHT", "BALLOON", "SLED",
    // Places (30)
    "HOUSE", "SCHOOL", "HOSPITAL", "STORE", "CHURCH", "BANK", "PARK", "BEACH", "MOUNTAIN", "RIVER",
    "LAKE", "OCEAN", "FOREST", "DESERT", "ISLAND", "FARM", "ZOO", "MUSEUM", "LIBRARY", "THEATER",
    "STADIUM", "AIRPORT", "STATION", "HOTEL", "RESTAURANT", "CAFE", "GYM", "POOL", "GARDEN", "BRIDGE",
    // Weather & Nature (20)
    "SUN", "MOON", "STAR", "CLOUD", "RAIN", "SNOW", "WIND", "STORM", "RAINBOW", "THUNDER",
    "LIGHTNING", "FOG", "ICE", "FIRE", "SMOKE", "TREE", "FLOWER", "GRASS", "ROCK", "SAND",
    // Clothing (20)
    "SHIRT", "PANTS", "DRESS", "SKIRT", "JACKET", "COAT", "SWEATER", "SHORTS", "JEANS", "SUIT",
    "HAT", "CAP", "SCARF", "GLOVES", "SOCKS", "SHOES", "BOOTS", "SANDALS", "BELT", "TIE",
    // Body Parts (15)
    "HEAD", "FACE", "EYE", "EAR", "NOSE", "MOUTH", "TOOTH", "HAND", "FINGER", "ARM",
    "LEG", "FOOT", "KNEE", "HEART", "BRAIN",
    // Sports & Activities (20)
    "SOCCER", "BASKETBALL", "BASEBALL", "FOOTBALL", "TENNIS", "GOLF", "SWIMMING", "RUNNING", "BOXING", "WRESTLING",
    "SKIING", "SKATING", "SURFING", "FISHING", "CAMPING", "HIKING", "DANCING", "SINGING", "PAINTING", "COOKING"
  ],
  normal: [
    // Science & Nature (45)
    "TELESCOPE", "MICROSCOPE", "LABORATORY", "EXPERIMENT", "CHEMISTRY", "BIOLOGY", "PHYSICS", "ASTRONOMY", "GEOLOGY", "ECOLOGY",
    "MOLECULE", "ATOM", "ELECTRON", "GRAVITY", "MAGNET", "ELECTRICITY", "RADIATION", "BACTERIA", "VIRUS", "VACCINE",
    "DINOSAUR", "FOSSIL", "VOLCANO", "EARTHQUAKE", "TSUNAMI", "HURRICANE", "TORNADO", "GLACIER", "CORAL REEF", "RAINFOREST",
    "ECOSYSTEM", "HABITAT", "PREDATOR", "EXTINCTION", "EVOLUTION", "PHOTOSYNTHESIS", "METABOLISM", "CHROMOSOME", "DNA", "PROTEIN",
    "OXYGEN", "CARBON", "NITROGEN", "HYDROGEN", "ELEMENT",
    // Movies & Entertainment (40)
    "HOLLYWOOD", "DIRECTOR", "PRODUCER", "SCREENPLAY", "ANIMATION", "DOCUMENTARY", "COMEDY", "HORROR", "THRILLER", "ROMANCE",
    "SUPERHERO", "VILLAIN", "SIDEKICK", "SOUNDTRACK", "PREMIERE", "BLOCKBUSTER", "FRANCHISE", "SEQUEL", "PREQUEL", "REMAKE",
    "STUNTMAN", "CELEBRITY", "PAPARAZZI", "RED CARPET", "OSCAR", "EMMY", "GRAMMY", "BROADWAY", "CONCERT", "FESTIVAL",
    "PODCAST", "STREAMING", "BINGE WATCH", "CLIFFHANGER", "PLOT TWIST", "FLASHBACK", "MONTAGE", "CAMEO", "CREDITS", "TRAILER",
    // Technology & Internet (40)
    "SOFTWARE", "HARDWARE", "DATABASE", "ALGORITHM", "ENCRYPTION", "FIREWALL", "BANDWIDTH", "DOWNLOAD", "UPLOAD", "STREAMING",
    "BLUETOOTH", "SATELLITE", "GPS", "VIRTUAL REALITY", "ARTIFICIAL", "AUTOMATION", "CRYPTOCURRENCY", "BLOCKCHAIN", "STARTUP", "APPLICATION",
    "BROWSER", "WEBSITE", "SOCIAL MEDIA", "HASHTAG", "VIRAL", "INFLUENCER", "CONTENT", "PLATFORM", "INTERFACE", "PIXEL",
    "RESOLUTION", "MEMORY", "PROCESSOR", "MOTHERBOARD", "GRAPHICS CARD", "OPERATING SYSTEM", "MALWARE", "HACKER", "PASSWORD", "USERNAME",
    // Geography & Travel (35)
    "CONTINENT", "PENINSULA", "ARCHIPELAGO", "MEDITERRANEAN", "CARIBBEAN", "PACIFIC", "ATLANTIC", "AMAZON", "SAHARA", "ANTARCTICA",
    "EQUATOR", "HEMISPHERE", "LATITUDE", "LONGITUDE", "TIMEZONE", "PASSPORT", "IMMIGRATION", "CUSTOMS", "EMBASSY", "TOURIST",
    "BACKPACKER", "ITINERARY", "DESTINATION", "LANDMARK", "MONUMENT", "CATHEDRAL", "PALACE", "FORTRESS", "RUINS", "SOUVENIR",
    "CURRENCY", "EXCHANGE RATE", "HOSTEL", "RESORT", "CRUISE",
    // Food & Cuisine (30)
    "SUSHI", "RAMEN", "CURRY", "PAELLA", "RISOTTO", "CROISSANT", "BAGUETTE", "PRETZEL", "HUMMUS", "FALAFEL",
    "GUACAMOLE", "KIMCHI", "TOFU", "TEMPURA", "FONDUE", "BRUSCHETTA", "TIRAMISU", "CHEESECAKE", "SOUFFLE", "MOUSSE",
    "ESPRESSO", "CAPPUCCINO", "SMOOTHIE", "COCKTAIL", "MARGARITA", "APPETIZER", "ENTREE", "DESSERT", "BUFFET", "CATERING",
    // Animals & Wildlife (30)
    "KANGAROO", "KOALA", "PLATYPUS", "GORILLA", "CHIMPANZEE", "ORANGUTAN", "LEOPARD", "CHEETAH", "PANTHER", "JAGUAR",
    "RHINOCEROS", "HIPPOPOTAMUS", "CROCODILE", "ALLIGATOR", "IGUANA", "CHAMELEON", "SALAMANDER", "OCTOPUS", "JELLYFISH", "SEAHORSE",
    "STINGRAY", "PELICAN", "FLAMINGO", "PEACOCK", "TOUCAN", "WOODPECKER", "HUMMINGBIRD", "PORCUPINE", "ARMADILLO", "SLOTH",
    // Health & Medicine (25)
    "HOSPITAL", "PHARMACY", "PRESCRIPTION", "ANTIBIOTIC", "SURGERY", "DIAGNOSIS", "SYMPTOM", "TREATMENT", "THERAPY", "REHABILITATION",
    "AMBULANCE", "EMERGENCY", "PARAMEDIC", "SURGEON", "SPECIALIST", "PEDIATRIC", "ORTHOPEDIC", "CARDIOLOGY", "NEUROLOGY", "PSYCHIATRY",
    "ALLERGY", "ASTHMA", "DIABETES", "ARTHRITIS", "MIGRAINE",
    // Business & Finance (25)
    "CORPORATION", "ENTREPRENEUR", "INVESTMENT", "PORTFOLIO", "DIVIDEND", "BANKRUPTCY", "MERGER", "ACQUISITION", "FRANCHISE", "MONOPOLY",
    "INFLATION", "RECESSION", "BUDGET", "REVENUE", "PROFIT", "MARKETING", "ADVERTISING", "BRANDING", "CONSUMER", "WHOLESALE",
    "RETAIL", "INVENTORY", "LOGISTICS", "HEADQUARTERS", "SUBSIDIARY",
    // Sports & Recreation (30)
    "MARATHON", "TRIATHLON", "GYMNASTICS", "VOLLEYBALL", "BADMINTON", "SQUASH", "CRICKET", "RUGBY", "LACROSSE", "ARCHERY",
    "FENCING", "EQUESTRIAN", "KAYAKING", "RAFTING", "SNORKELING", "SCUBA DIVING", "BUNGEE JUMPING", "SKYDIVING", "PARAGLIDING", "ROCK CLIMBING",
    "SNOWBOARDING", "BOBSLED", "CURLING", "BIATHLON", "DECATHLON", "CHAMPIONSHIP", "TOURNAMENT", "PLAYOFFS", "SEMIFINALS", "FINALS"
  ],
  hard: [
    // Advanced Science (50)
    "QUANTUM", "THERMODYNAMICS", "ELECTROMAGNETISM", "RELATIVITY", "ENTROPY", "KINETICS", "CATALYST", "ISOTOPE", "RADIOACTIVE", "NUCLEAR",
    "SUPERCONDUCTOR", "NANOTECHNOLOGY", "GENOME", "MUTATION", "HEREDITARY", "NEUROSCIENCE", "COGNITIVE", "PATHOLOGY", "EPIDEMIOLOGY", "IMMUNOLOGY",
    "PHARMACOLOGY", "TOXICOLOGY", "BIOCHEMISTRY", "ORGANIC CHEMISTRY", "INORGANIC", "POLYMER", "ALLOY", "SEMICONDUCTOR", "CAPACITOR", "TRANSISTOR",
    "OSCILLATION", "FREQUENCY", "WAVELENGTH", "SPECTRUM", "REFRACTION", "DIFFRACTION", "POLARIZATION", "IONIZATION", "OXIDATION", "REDUCTION",
    "SYNTHESIS", "ANALYSIS", "HYPOTHESIS", "CORRELATION", "REGRESSION", "DEVIATION", "VARIABLE", "CONSTANT", "THEOREM", "AXIOM",
    // Philosophy & Psychology (40)
    "PHILOSOPHY", "METAPHYSICS", "EPISTEMOLOGY", "ONTOLOGY", "ETHICS", "MORALITY", "AESTHETICS", "LOGIC", "RATIONALISM", "EMPIRICISM",
    "EXISTENTIALISM", "NIHILISM", "STOICISM", "HEDONISM", "UTILITARIANISM", "DETERMINISM", "CONSCIOUSNESS", "SUBCONSCIOUSNESS", "PERCEPTION", "COGNITION",
    "INTUITION", "RATIONALITY", "BEHAVIORAL", "PSYCHOANALYSIS", "NEUROSIS", "PHOBIA", "TRAUMA", "REPRESSION", "PROJECTION", "SUBLIMATION",
    "CONDITIONING", "REINFORCEMENT", "MOTIVATION", "PERSONALITY", "TEMPERAMENT", "INTROVERT", "EXTROVERT", "NARCISSISM", "EMPATHY", "ALTRUISM",
    // History & Politics (40)
    "CIVILIZATION", "DYNASTY", "MONARCHY", "ARISTOCRACY", "DEMOCRACY", "REPUBLIC", "COMMUNISM", "CAPITALISM", "SOCIALISM", "FASCISM",
    "REVOLUTION", "INDEPENDENCE", "COLONIALISM", "IMPERIALISM", "NATIONALISM", "SOVEREIGNTY", "CONSTITUTION", "AMENDMENT", "LEGISLATION", "JURISDICTION",
    "DIPLOMACY", "TREATY", "ALLIANCE", "SANCTION", "EMBARGO", "PROPAGANDA", "IDEOLOGY", "BUREAUCRACY", "CORRUPTION", "REFERENDUM",
    "SUFFRAGE", "SEGREGATION", "EMANCIPATION", "REFORMATION", "RENAISSANCE", "ENLIGHTENMENT", "INDUSTRIAL", "MEDIEVAL", "FEUDALISM", "CRUSADE",
    // Economics & Finance (35)
    "MACROECONOMICS", "MICROECONOMICS", "MONETARISM", "KEYNESIAN", "FISCAL POLICY", "MONETARY POLICY", "QUANTITATIVE", "DERIVATIVES", "COMMODITIES", "SECURITIES",
    "ARBITRAGE", "SPECULATION", "VOLATILITY", "LIQUIDITY", "AMORTIZATION", "DEPRECIATION", "APPRECIATION", "COLLATERAL", "LIABILITY", "EQUITY",
    "LEVERAGE", "HEDGE FUND", "VENTURE CAPITAL", "PRIVATE EQUITY", "IPO", "VALUATION", "AUDIT", "COMPLIANCE", "FIDUCIARY", "ANTITRUST",
    "SUBSIDY", "TARIFF", "QUOTA", "DEFICIT", "SURPLUS",
    // Literature & Arts (35)
    "PROTAGONIST", "ANTAGONIST", "ALLEGORY", "METAPHOR", "SYMBOLISM", "IRONY", "SATIRE", "PARODY", "NARRATIVE", "RHETORIC",
    "PROSE", "VERSE", "SONNET", "EPIC", "TRAGEDY", "COMEDY", "DRAMA", "MEMOIR", "BIOGRAPHY", "AUTOBIOGRAPHY",
    "IMPRESSIONISM", "EXPRESSIONISM", "SURREALISM", "CUBISM", "MINIMALISM", "BAROQUE", "GOTHIC", "NEOCLASSICAL", "CONTEMPORARY", "AVANT GARDE",
    "COMPOSITION", "PERSPECTIVE", "SILHOUETTE", "MOSAIC", "FRESCO",
    // Law & Government (30)
    "JURISPRUDENCE", "LITIGATION", "PROSECUTION", "DEFENDANT", "PLAINTIFF", "VERDICT", "ACQUITTAL", "CONVICTION", "APPEAL", "PRECEDENT",
    "TESTIMONY", "AFFIDAVIT", "SUBPOENA", "INJUNCTION", "WARRANT", "INDICTMENT", "ARRAIGNMENT", "BAIL", "PROBATION", "PAROLE",
    "STATUTE", "ORDINANCE", "REGULATION", "COMPLIANCE", "ENFORCEMENT", "TRIBUNAL", "ARBITRATION", "MEDIATION", "SETTLEMENT", "DAMAGES",
    // Medicine & Biology (35)
    "CARDIOVASCULAR", "RESPIRATORY", "GASTROINTESTINAL", "MUSCULOSKELETAL", "ENDOCRINE", "LYMPHATIC", "NERVOUS SYSTEM", "CIRCULATORY", "DIGESTIVE", "EXCRETORY",
    "INFLAMMATION", "INFECTION", "CHRONIC", "ACUTE", "BENIGN", "MALIGNANT", "METASTASIS", "REMISSION", "PROGNOSIS", "BIOPSY",
    "TRANSFUSION", "TRANSPLANT", "PROSTHETIC", "ANESTHESIA", "ANTISEPTIC", "STERILIZATION", "INCUBATION", "CONTAGIOUS", "HEREDITARY", "AUTOIMMUNE",
    "CARCINOGEN", "ANTIOXIDANT", "CHOLESTEROL", "INSULIN", "ADRENALINE",
    // Technology & Computing (35)
    "CYBERSECURITY", "INFRASTRUCTURE", "ARCHITECTURE", "SCALABILITY", "REDUNDANCY", "VIRTUALIZATION", "CONTAINERIZATION", "MICROSERVICES", "API", "PROTOCOL",
    "ENCRYPTION", "DECRYPTION", "AUTHENTICATION", "AUTHORIZATION", "CERTIFICATE", "COMPRESSION", "DECOMPRESSION", "OPTIMIZATION", "DEBUGGING", "DEPLOYMENT",
    "REPOSITORY", "VERSION CONTROL", "INTEGRATION", "REGRESSION", "ITERATION", "RECURSION", "CONCURRENCY", "PARALLELISM", "LATENCY", "THROUGHPUT",
    "CACHE", "BUFFER", "STACK", "QUEUE", "BINARY"
  ],
  insane: [
    // Obscure Vocabulary (60)
    "SESQUIPEDALIAN", "DEFENESTRATION", "LOQUACIOUS", "GARRULOUS", "PERSPICACIOUS", "MAGNANIMOUS", "PUSILLANIMOUS", "SUPERCILIOUS", "OBSEQUIOUS", "SYCOPHANT",
    "EPHEMERAL", "ETHEREAL", "INEFFABLE", "NEFARIOUS", "PERFIDIOUS", "MENDACIOUS", "VERACIOUS", "PULCHRITUDINOUS", "EGREGIOUS", "GREGARIOUS",
    "FASTIDIOUS", "METICULOUS", "SCRUPULOUS", "PUNCTILIOUS", "LITIGIOUS", "CAPRICIOUS", "AUSPICIOUS", "PROPITIOUS", "PERNICIOUS", "OSTENTATIOUS",
    "PRETENTIOUS", "CONTENTIOUS", "SURREPTITIOUS", "SUPERSTITIOUS", "EXPEDITIOUS", "JUDICIOUS", "INJUDICIOUS", "OFFICIOUS", "EFFICACIOUS", "PERSPICUOUS",
    "CONSPICUOUS", "INNOCUOUS", "AMBIGUOUS", "CONTIGUOUS", "UBIQUITOUS", "INIQUITOUS", "SOLICITOUS", "PRECIPITOUS", "CIRCUITOUS", "FORTUITOUS",
    "GRATUITOUS", "SUPERFLUOUS", "MELLIFLUOUS", "LUGUBRIOUS", "SALUBRIOUS", "QUERULOUS", "TREMULOUS", "CREDULOUS", "INCREDULOUS", "PENDULOUS",
    // Philosophy & Abstract (50)
    "EPISTEMOLOGICAL", "PHENOMENOLOGICAL", "HERMENEUTICS", "DIALECTICAL", "TELEOLOGICAL", "DEONTOLOGICAL", "CONSEQUENTIALISM", "TRANSCENDENTALISM", "POSTMODERNISM", "STRUCTURALISM",
    "DECONSTRUCTIONISM", "RELATIVISM", "ABSOLUTISM", "SOLIPSISM", "DUALISM", "MONISM", "PLURALISM", "REDUCTIONISM", "HOLISM", "PRAGMATISM",
    "POSITIVISM", "SKEPTICISM", "AGNOSTICISM", "ATHEISM", "THEISM", "PANTHEISM", "PANENTHEISM", "ANIMISM", "TOTEMISM", "SYNCRETISM",
    "ANTINOMIANISM", "ANTIDISESTABLISHMENTARIANISM", "FLOCCINAUCINIHILIPILIFICATION", "PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS", "HIPPOPOTOMONSTROSESQUIPPEDALIOPHOBIA", "SUPERCALIFRAGILISTICEXPIALIDOCIOUS", "PSEUDOPSEUDOHYPOPARATHYROIDISM", "THYROPARATHYROIDECTOMIZED", "SPECTROPHOTOFLUOROMETRICALLY", "PSYCHONEUROENDOCRINOLOGICAL",
    "COUNTERREVOLUTIONARIES", "DEINSTITUTIONALIZATION", "ELECTROENCEPHALOGRAPHICALLY", "IMMUNOELECTROPHORETICALLY", "INTERNATIONALIZATION", "OTORHINOLARYNGOLOGICAL", "OVERINTELLECTUALIZATION", "PSYCHOPHARMACOLOGICAL", "REINDUSTRIALIZATION", "TRANSUBSTANTIATION",
    // Scientific Jargon (50)
    "BIOLUMINESCENCE", "CHEMILUMINESCENCE", "PHOSPHORESCENCE", "FLUORESCENCE", "IRIDESCENCE", "OPALESCENCE", "EFFERVESCENCE", "LUMINESCENCE", "INCANDESCENCE", "QUIESCENCE",
    "SENESCENCE", "OBSOLESCENCE", "CONVALESCENCE", "COALESCENCE", "ACQUIESCENCE", "EVANESCENCE", "DELIQUESCENCE", "INTUMESCENCE", "TUMESCENCE", "DETUMESCENCE",
    "PROPRIOCEPTION", "NOCICEPTION", "INTEROCEPTION", "EXTEROCEPTION", "MAGNETOCEPTION", "ELECTRORECEPTION", "MECHANORECEPTION", "CHEMORECEPTION", "THERMORECEPTION", "PHOTORECEPTION",
    "NEUROPLASTICITY", "SYNAPTIC", "AXONAL", "DENDRITIC", "GLIAL", "MITOCHONDRIAL", "RIBOSOMAL", "LYSOSOMAL", "ENDOPLASMIC", "CYTOPLASMIC",
    "EPIGENETIC", "PHYLOGENETIC", "ONTOGENETIC", "MORPHOGENETIC", "PATHOGENETIC", "IATROGENIC", "CARCINOGENIC", "MUTAGENIC", "TERATOGENIC", "HALLUCINOGENIC",
    // Literary & Rhetorical (40)
    "ONOMATOPOEIA", "SYNECDOCHE", "METONYMY", "CATACHRESIS", "HYPERBOLE", "LITOTES", "OXYMORON", "PARADOX", "ANTITHESIS", "CHIASMUS",
    "ANAPHORA", "EPISTROPHE", "ANADIPLOSIS", "POLYSYNDETON", "ASYNDETON", "ZEUGMA", "SYLLEPSIS", "HENDIADYS", "TMESIS", "HYPERBATON",
    "ANACOLUTHON", "APOPHASIS", "PARALEPSIS", "PROSOPOPOEIA", "ANTHROPOMORPHISM", "PERSONIFICATION", "APOSTROPHE", "EUPHEMISM", "DYSPHEMISM", "PERIPHRASIS",
    "PLEONASM", "TAUTOLOGY", "MALAPROPISM", "SPOONERISM", "NEOLOGISM", "PORTMANTEAU", "PALINDROME", "ANAGRAM", "ACRONYM", "INITIALISM",
    // Rare & Unusual (50)
    "PETRICHOR", "PHOSPHENES", "PAREIDOLIA", "APOPHENIA", "SYNESTHESIA", "JAMAIS VU", "PRESQUE VU", "DEJA VU", "SONDER", "MONACHOPSIS",
    "KENOPSIA", "MAUERBAUERTRAURIGKEIT", "JOUSKA", "CHRYSALISM", "VELLICHOR", "RUBATOSIS", "GNOSSIENNE", "ANECDOCHE", "ELLIPSISM", "KUEBIKO",
    "LACHESISM", "EXULANSIS", "ADRONITIS", "LIBEROSIS", "ALTSCHMERZ", "OCCHIOLISM", "OPIA", "KLEXOS", "VEMÖDALEN", "ANEMOIA",
    "SCHADENFREUDE", "WELTSCHMERZ", "ZEITGEIST", "WANDERLUST", "FERNWEH", "SEHNSUCHT", "TORSCHLUSSPANIK", "FREMDSCHAMEN", "BACKPFEIFENGESICHT", "KUMMERSPECK",
    "TREPPENWITZ", "WALDEINSAMKEIT", "GEMUTLICHKEIT", "FINGERSPITZENGEFUHL", "VERSCHLIMMBESSERN", "KOPFKINO", "OHRWURM", "INNERER SCHWEINEHUND", "LUFTSCHLOSS", "KUDDELMUDDEL",
    // Technical & Specialized (50)
    "JUXTAPOSITION", "EXTRAPOLATION", "INTERPOLATION", "APPROXIMATION", "DISAMBIGUATION", "CONTEXTUALIZATION", "COMPARTMENTALIZATION", "CONCEPTUALIZATION", "OPERATIONALIZATION", "INSTITUTIONALIZATION",
    "PROFESSIONALIZATION", "BUREAUCRATIZATION", "COMMERCIALIZATION", "COMMODIFICATION", "GENTRIFICATION", "STRATIFICATION", "DIVERSIFICATION", "SIMPLIFICATION", "AMPLIFICATION", "RECTIFICATION",
    "RATIFICATION", "GRATIFICATION", "MYSTIFICATION", "JUSTIFICATION", "IDENTIFICATION", "CLASSIFICATION", "QUALIFICATION", "DISQUALIFICATION", "EXEMPLIFICATION", "PERSONIFICATION",
    "REIFICATION", "DEIFICATION", "VILIFICATION", "GLORIFICATION", "PURIFICATION", "SANCTIFICATION", "MORTIFICATION", "FORTIFICATION", "CERTIFICATION", "VERIFICATION",
    "FALSIFICATION", "CODIFICATION", "MODIFICATION", "NOTIFICATION", "SPECIFICATION", "SIGNIFICATION", "MAGNIFICATION", "CALCIFICATION", "OSSIFICATION", "PETRIFICATION"
  ]
};

const POINTS = { easy: 10, normal: 20, hard: 25, insane: 50 };

const DIFFICULTY_DISTRIBUTIONS = {
  easy: { easy: 0.7, normal: 0.2, hard: 0.1, insane: 0 },
  normal: { easy: 0, normal: 0.7, hard: 0.3, insane: 0 },
  hard: { easy: 0.1, normal: 0.2, hard: 0.7, insane: 0 },
  insane: { easy: 0, normal: 0.2, hard: 0.2, insane: 0.6 },
  mixed: { easy: 0.25, normal: 0.25, hard: 0.25, insane: 0.25 },
};

function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

function getWordsForDifficulty(difficulty, totalWords = 16) {
  const distribution = DIFFICULTY_DISTRIBUTIONS[difficulty] || DIFFICULTY_DISTRIBUTIONS.mixed;
  const selectedWords = [];

  const counts = {
    easy: Math.round(totalWords * distribution.easy),
    normal: Math.round(totalWords * distribution.normal),
    hard: Math.round(totalWords * distribution.hard),
    insane: Math.round(totalWords * distribution.insane),
  };

  // Adjust for rounding errors
  const totalCount = counts.easy + counts.normal + counts.hard + counts.insane;
  if (totalCount !== totalWords) {
    const categories = ['easy', 'normal', 'hard', 'insane'].filter(cat => counts[cat] > 0);
    if (categories.length > 0) {
      counts[categories[0]] += (totalWords - totalCount);
    }
  }

  // Select random words from each difficulty level
  for (const [level, count] of Object.entries(counts)) {
    if (count > 0 && WORD_LISTS[level]) {
      const shuffled = shuffleArray(WORD_LISTS[level]);
      for (let i = 0; i < count && i < shuffled.length; i++) {
        selectedWords.push({
          word: shuffled[i],
          points: POINTS[level],
          difficulty: level
        });
      }
    }
  }

  return shuffleArray(selectedWords);
}

module.exports = { WORD_LISTS, POINTS, getWordsForDifficulty };
